keepcalm:
  security:
    jwt:
      issuer: Keepcalm Auth
      audience: Keepcalm
      secret: s3cretP@ssw0rd
    endpoints:
      admin:
        - "/api/salary/**"
      user:
        - "/api/document/**"
      unsecured:
        - "/unsecure"
